services:
  postgres:
    image: postgres:16-alpine
    container_name: clientix-postgres
    environment:
      POSTGRES_USER: clientix
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clientix
    ports: ["5433:5432"]
    volumes: [postgres_data:/var/lib/postgresql/data]

  redis:
    image: redis:7-alpine
    container_name: clientix-redis
    ports: ["6379:6379"]

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: clientix-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: clientix
      RABBITMQ_DEFAULT_PASS: postgres
    ports: ["5672:5672", "15672:15672"]

volumes:
  postgres_data: