FROM node:20-alpine AS build
WORKDIR /app
COPY web/master/package.json web/master/package-lock.json* ./
RUN npm ci || npm install
COPY web/master/ ./
RUN npm run build

FROM nginx:alpine AS runtime
COPY --from=build /app/dist /usr/share/nginx/html
COPY web/master/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]